

function poda() {
    var titulo = document.querySelector('.tituloTextPost h1');
    titulo.textContent = 'PODA';
    
    var conteudo = document.querySelector('.contentTextPost h4');
    conteudo.innerHTML = 'A poda da Hera Inglesa é uma prática importante para manter a planta saudável e com um aspecto estético agradável. Aqui estão algumas dicas gerais sobre como podar essa planta:<br><br>Escolha o momento certo: A melhor época para podar a Hera Inglesa é durante a primavera e o verão, quando a planta está em crescimento ativo. Evite podar durante o outono e o inverno, quando a planta está inativa, pois isso pode enfraquecê-la.<br><br>Determine o objetivo da poda: Antes de começar a poda, determine o que você deseja alcançar. A poda pode ser feita para controlar o tamanho e a forma da planta, para incentivar o crescimento de novos brotos ou para remover partes danificadas ou doentes.<br><br>Corte os ramos excessivos: Se a sua Hera Inglesa está ficando muito grande, você pode cortar os ramos excessivos para controlar o tamanho da planta. Corte os ramos mais longos até um ponto onde você deseja que a planta pare de crescer.<br><br>Remova as folhas e galhos mortos: Se você notar folhas ou galhos mortos em sua Hera Inglesa, remova-os imediatamente. Isso ajudará a prevenir a propagação de doenças e manterá a planta saudável.<br><br>Não exagere na poda: Tenha cuidado para não podar em excesso a Hera Inglesa. A planta precisa de folhas para fazer fotossíntese e produzir alimento, então evite remover mais de 20% da folhagem em uma única poda.<br><br>Lembre-se de usar ferramentas de poda limpas e afiadas para evitar danificar a planta. E se você não se sentir confortável fazendo a poda sozinho, contrate um profissional capacitado para fazer o trabalho.'
  }
  
function solo() {
    var titulo = document.querySelector('.tituloTextPost h1');
    titulo.textContent = 'SOLO';
    
    var conteudo = document.querySelector('.contentTextPost h4');
    conteudo.innerHTML = 'O solo é um fator importante para o cultivo saudável da Hera Inglesa. Esta planta prefere solos úmidos, férteis e bem drenados. Aqui estão algumas informações importantes sobre o solo adequado para a Hera Inglesa:<br><br>pH do solo: A Hera Inglesa prefere solos ácidos a neutros, com um pH entre 5,5 e 7,0.<br><br>Drenagem: O solo deve ser bem drenado para evitar que as raízes fiquem encharcadas. Se o solo estiver muito compactado ou argiloso, adicione areia e matéria orgânica para melhorar a drenagem.<br><br>Umidade: A Hera Inglesa gosta de solos úmidos, mas não encharcados. Verifique a umidade do solo regularmente e regue a planta sempre que a camada superior do solo começar a secar.<br><br>Nutrientes: A Hera Inglesa precisa de uma quantidade adequada de nutrientes para crescer saudável. Adicione matéria orgânica, como composto ou esterco, ao solo para melhorar sua fertilidade.<br><br>Luz solar: A Hera Inglesa é uma planta de sombra parcial, que prefere locais com pouca luz solar direta. Ela pode tolerar algumas horas de sol direto pela manhã ou à tarde, mas muita luz solar pode causar queimaduras nas folhas.<br><br>Ao plantar a Hera Inglesa, cave um buraco ligeiramente maior que o tamanho do torrão da planta e adicione um pouco de adubo orgânico e terra nova ao solo. Certifique-se de que as raízes da planta estejam firmes e cobertas com solo. Regue bem a planta depois de plantá-la e continue regando regularmente para manter o solo úmido.'
  }
function adubagem() {
    var titulo = document.querySelector('.tituloTextPost h1');
    titulo.textContent = 'ADUBAGEM';
    
    var conteudo = document.querySelector('.contentTextPost h4');
    conteudo.innerHTML = 'A adubação é um aspecto importante para manter a Hera Inglesa saudável e com um bom crescimento. Aqui estão algumas informações importantes sobre como adubar essa planta:<br><br>Frequência: A Hera Inglesa deve ser adubada regularmente durante a temporada de crescimento ativo, que geralmente é de março a setembro. Você pode adubar a planta uma vez por mês durante este período.<br><br>Tipo de adubo: Use um adubo equilibrado, com uma proporção de nutrientes NPK de 10-10-10 ou 20-20-20. Você também pode usar um adubo orgânico, como composto ou esterco bem decomposto.<br><br>Quantidade de adubo: Aplique cerca de 1 colher de sopa de adubo por pé de planta, espalhando-o uniformemente sobre a superfície do solo.<br><br>Aplicação de adubo: Aplique o adubo em torno da base da planta, mantendo-o a uma distância de cerca de 5 cm do caule para evitar queimar as raízes.<br><br>Rega: Após a aplicação do adubo, regue bem a planta para permitir que o adubo penetre no solo e alcance as raízes.<br><br>Lembre-se de não exagerar na quantidade de adubo aplicado, pois isso pode prejudicar a planta. A Hera Inglesa é uma planta resistente que pode crescer bem sem muita adubação, então use adubo com moderação e regue regularmente para manter a planta saudável e com um bom crescimento.';
  }
  
function plant() {
    var titulo = document.querySelector('.tituloTextPost h1');
    titulo.textContent = 'Hera Inglesa';
    
    var conteudo = document.querySelector('.contentTextPost h4');
    conteudo.innerHTML = 'A Hera Inglesa (Hedera helix) é uma planta trepadeira perene originária da Europa e da Ásia Ocidental. Ela é amplamente cultivada em todo o mundo como planta ornamental e é frequentemente usada para cobrir paredes, cercas e outras estruturas.<br><br>A Hera Inglesa é uma planta versátil, que pode ser cultivada tanto em áreas ensolaradas quanto sombreadas. Ela é uma trepadeira vigorosa, capaz de se agarrar a superfícies verticais por meio de raízes adesivas. As folhas são verdes escuras e brilhantes, com um formato característico em forma de coração e uma textura aveludada na parte inferior.<br><br>Além de sua beleza ornamental, a Hera Inglesa tem sido usada por seus benefícios medicinais. Suas folhas contêm compostos que possuem propriedades anti-inflamatórias, expectorantes e antiespasmódicas, tornando-a útil no tratamento de várias condições respiratórias, como a bronquite e a asma.<br><br>No entanto, é importante notar que a Hera Inglesa é tóxica quando ingerida e pode causar irritação na pele em algumas pessoas. Portanto, é recomendável tomar precauções ao manusear a planta e mantê-la fora do alcance de crianças e animais de estimação.';
  }
function pragas() {
    var titulo = document.querySelector('.tituloTextPost h1');
    titulo.textContent = 'PRAGAS E DOENÇAS';
    
    var conteudo = document.querySelector('.contentTextPost h4');
    conteudo.innerHTML = 'A Hera Inglesa é uma planta relativamente resistente a pragas e doenças, mas ainda assim pode ser afetada por alguns problemas. Aqui estão alguns dos problemas mais comuns que podem afetar a Hera Inglesa:<br><br>Cochonilhas: Essas pequenas pragas podem aparecer nas folhas, caules e flores da Hera Inglesa. Elas se alimentam da seiva da planta e podem causar danos significativos. Use um spray de óleo mineral ou sabão inseticida para eliminá-las.<br><br>Ácaros: Ácaros são pequenos insetos que sugam a seiva da planta, causando manchas brancas ou amareladas nas folhas. Use um spray de óleo de nim ou enxofre para controlá-los.<br><br>Pulgões: Esses pequenos insetos verdes ou pretos se alimentam da seiva da planta, causando enrugamento e deformação das folhas. Use um spray de sabão inseticida ou óleo de nim para controlá-los.<br><br>Ferrugem: Esta é uma doença fúngica que pode afetar a Hera Inglesa. Ela causa manchas amarelas nas folhas e pode fazer com que as folhas caiam. Remova as folhas infectadas e aplique um fungicida para controlar a infecção.<br><br>Oídio: Esta é outra doença fúngica que pode afetar a Hera Inglesa. Ela causa um revestimento branco em pó nas folhas e pode fazer com que as folhas caiam. Use um fungicida para controlar a infecção.<br><br>Para prevenir problemas com pragas e doenças, é importante manter a Hera Inglesa saudável e bem cuidada. Certifique-se de que a planta esteja em um local bem iluminado, mas protegido da luz solar direta, e que o solo esteja úmido, mas não encharcado. Evite regar a planta por cima das folhas para evitar a proliferação de doenças fúngicas.';
  }
  